apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xuhhy51n6-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xuhhy51n6-java-springboot-gitops